# name: First Workflow 
# on: workflow_dispatch   # This means user can manually Start the Workflow
# jobs: 
#   first_job:
#     runs-on:  ubuntu-latest
#     steps:
#       - name: Print Greetings 
#         run: echo "Helo World "
#       - name: Print goodbye
#         run: echo "Done Good Bye!"
name: First Workflow 
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'     
        required: true
        default: 'prod'
      branch:
        description: 'Define branch name'     
        required: true
        default: 'master'