# name: First Workflow 
# on: workflow_dispatch   # This means user can manually Start the Workflow
# jobs: 
#   first_job:
#     runs-on:  ubuntu-latest
#     steps:
#       - name: Print Greetings 
#         run: echo "Helo World "
#       - name: Print goodbye
#         run: echo "Done Good Bye!"
name: Build Command
on:
  repository_dispatch:
    types: [build-command]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          path: ${{ github.event.repository.name }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
