name: Create EventBridge Rule

on:
  push:
    branches:
      - main

env:
  TENANT_ID: D9vGe8C3JFUAAkeO
  AWS_REGION: us-west-2

jobs:
  create-eventbridge-rule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create SNS Topic
        id: create-sns-topic
        run: |
          aws sns create-topic \
          --name "${{ env.TENANT_ID }}-sns-topic" \
          --output text \
          --query 'TopicArn' > topic_arn.txt

      - name: Get SNS Topic ARN
        run: echo "SNS Topic ARN: $(cat topic_arn.txt)"

      - name: Create EventBridge Rule
        run: |
          aws events put-rule \
          --name "${{ env.TENANT_ID }}-event-rule" \
          --event-pattern file://event-pattern.json

      - name: Add SNS Target to EventBridge Rule
        run: |
          TOPIC_ARN=$(cat topic_arn.txt)
          
          aws events put-targets \
          --rule "${{ env.TENANT_ID }}-event-rule" \
          --targets "Id"="1", "Arn"="$TOPIC_ARN"
