name: Create AWS Resources

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: ap-south-1

jobs:
  create-resources:
    runs-on: ubuntu-latest
    environment: develop-env

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Create S3 Bucket
        run: |
          aws s3 mb s3://my-bucket-${{ env.AWS_REGION }}

      - name: Create SNS Topic
        run: |
          aws sns create-topic \
          --name my-topic \
          --output text \
          --query 'TopicArn' \
          | tee topic-arn.txt

      - name: Create SQS Queue
        run: |
          aws sqs create-queue \
          --queue-name my-queue \
          --output text \
          --query 'QueueUrl' \
          | tee queue-url.txt

      - name: Add SNS Subscription to SQS Queue
        run: |
          TOPIC_ARN=$(cat topic-arn.txt)
          QUEUE_URL=$(cat queue-url.txt)
          aws sns subscribe \
          --topic-arn "$TOPIC_ARN" \
          --protocol sqs \
          --notification-endpoint "$QUEUE_URL"
